### ISSUE TITLE
Lezione giovedì 5 aprile

### ISSUE THREAD

**Issue by Malistor** [uniroma2/TTLE-2018#2]
Come da titolo, non ricordo se abbiamo lezione giovedì 5 aprile o meno

**Comment by Malistor** [comment]
@grammaton

**Comment by grammaton** [comment]
ciao,
no giovedì non ci sarà lezione.
per le comunicazioni di servizio utilizziamo la [discussion board](https://github.com/orgs/uniroma2/teams/ttle2018) del nostro team, lasciando le ISSUES alla risoluzione di problemi sui contenuti.

A presto! (giovedì 12)
